config/routes.rb
Rails.application.routes.draw do

  root 'site/pages#home'

  devise_for :users
  get 'users/dashboard', as: 'user_root'

  namespace :users do
    resources :posts, except: [:show]
  end

  scope module: 'site' do
    resources :posts,  only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site/pages_controller.rb
class Site::PagesController < SiteController
  def home
    @posts = Post.all
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  layout 'site'
  before_action :all_pages_data

  private

  # информация которая будет на всех страницах
  def all_pages_data; end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < UsersController

  before_action :get_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def edit; end

  def update
    @post.update_attributes(post_params)
    redirect_back(fallback_location: user_root_path)
  end

  def destroy
    @post.destroy
    redirect_back(fallback_location: user_root_path)
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new
    post.assign_attributes(post_params)
    if post.save
      redirect_to edit_users_post_path(post)
    else
      redirect_back(fallback_location: user_root_path)
    end
  end

  private

  def get_post
    @post = Post.find(params[:id])
  end


  def post_params
    params.require(:post).permit(:title, :description, :meta_title, :meta_description, :meta_keywords)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :check_user_permissions

  layout "user"

  def after_sign_in_path_for(resource)
    user_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  def dashboard
    render 'users/dashboard'
  end

  def check_user_permissions
    fail(AccessDenied.new) unless UserPolicy.new(current_user).access_to_admin_panel?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp - общедоступная часть</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'site', media: 'all' %>
</head>

<body>
<%= yield %>
<%= javascript_include_tag 'site' %>
</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Testapp - панель управления администратора</title>
  <%= favicon_link_tag "user/template/favicon.ico" %>
  <%= stylesheet_link_tag 'user' %>
  <%= csrf_meta_tags %>
</head>

<body class="fixed-nav sticky-footer admin-panel <%= yield(:body_class) %>" id="page-top">
<nav class="navbar navbar-expand-lg navbar-dark bg-default fixed-top" id="mainNav">
  <a class="navbar-brand" href="/users/dashboard">
    <%= image_tag "user/template/logo2.png", width: 150, height: 36 %>
  </a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <%= render "layouts/user/sidebar" %>
    <%= render "layouts/user/header" %>
  </div>
</nav>

<div class="content-wrapper">
  <%= yield %>
</div>

<%= render "layouts/user/footer" %>
<%= render "layouts/user/logout_modal" %>
<%= javascript_include_tag 'user' %>
</body>

</html>

app/views/layouts/user/_footer.html.erb
<footer class="sticky-footer">
  <div class="container">
    <div class="text-center">
      <small>Copyright © TestApp <%= Time.new.year == 2019 ? Time.new.year : "2019 - #{Time.new.year}" %></small>
    </div>
  </div>
</footer>

app/views/layouts/user/_header.html.erb
<ul class="navbar-nav sidenav-toggler">
  <li class="nav-item">
    <a class="nav-link text-center" id="sidenavToggler">
      <i class="fa fa-fw fa-angle-left"></i>
    </a>
  </li>
</ul>
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
      <i class="fa fa-fw fa-sign-out"></i>Выйти</a>
  </li>
</ul>

app/views/layouts/user/_logout_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Подтвердите выход</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Выйти из аккаунта администратора ?</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Отмена</button>
        <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/user/_sidebar.html.erb
<ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
    <a class="nav-link" href="/users/dashboard">
      <i class="fa fa-fw fa-tachometer"></i>
      <span class="nav-link-text">Консоль</span>
    </a>
  </li>

  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
    <a class="nav-link" href="/users/posts">
      <i class="fa fa-fw fa-rss"></i>
      <span class="nav-link-text">Записи</span>
    </a>
  </li>
</ul>

app/views/site/pages/home.html.erb
<h3>This is home page</h3>

app/views/users/dashboard.html.erb
<% provide(:body_class, 'dashboard') %>
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="/">TestApp</a>
    </li>
    <li class="breadcrumb-item active">Консоль</li>
  </ol>
  <h2></h2>
  <div class="box_general padding_bottom">
    <div class="header_box version_2">
      <h2>Консоль</h2>
    </div>
    <h3>Здесь отображается актуальная информация о проекте</h3>
    <p>Доступ к аккаунту администратора: user@test.ru | 12345</p>

  </div>
</div>

app/views/users/posts/edit.html.erb
<% provide(:body_class, 'posts-edit') %>
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="/users/dashboard">Консоль</a>
    </li>
    <li class="breadcrumb-item">
      <a href="/users/post_categories">Записи</a>
    </li>
    <li class="breadcrumb-item active"><%= @post.title %></li>
  </ol>

  <%= form_with model: @post, url: users_post_path, local: true do |f| %>
    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2>Основная информация</h2>
        <%= f.submit "Обновить", class: "btn_1 small pull-right" %>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Название</label>
            <%= f.text_field :title, class: "form-control", placeholder: "Название записи" %>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Описание</label>
            <%= f.text_area :description, class: "form-control tinymce", placeholder: "Описание", rows: 15 %>
          </div>
        </div>
      </div>
    </div>


    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2>SEO</h2>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Meta title</label>
            <%= f.text_field :meta_title, class: "form-control", placeholder: "meta title" %>
          </div>
          <div class="form-group">
            <label>Meta description</label>
            <%= f.text_area :meta_description, class: "form-control", placeholder: "meta description" %>
          </div>
          <div class="form-group">
            <label>Meta keywords</label>
            <%= f.text_area :meta_keywords, class: "form-control", placeholder: "meta keywords" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="buttons_container">
    <ul>
      <li><%= link_to "Назад", users_posts_path, class: 'btn_1 gray small' %></li>
    </ul>
  </div>
</div>

app/views/users/posts/index.html.erb
<% provide(:body_class, 'posts-index') %>
<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="/users/dashboard">Консоль</a>
    </li>
    <li class="breadcrumb-item active">Записи</li>
  </ol>
  <div class="card mb-3">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
          <tr>
            <th >Название</th>
            <th >Категория</th>
            <th style="width: 20%">Ссылки</th>
          </tr>
          </thead>
          <tfoot>
          <tr>
            <th>Названия</th>
            <th >Категория</th>
            <th style="width: 20%">Ссылки</th>
          </tr>
          </tfoot>
          <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td>
                <%= link_to post.title, post_path(post), target: '_blank' %><br/>
              </td>
              <td>
                --
              </td>
              <td>
                <%= link_to "Редактировать", edit_users_post_path(post) %> |
                <%= link_to "Удалить", users_post_path(post), method: :delete,
                            data: { confirm: "Удалить запись '#{  post.title}' ?" } %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="buttons_container">
    <ul>
      <li><%= link_to "Добавить", new_users_post_path, class: 'btn_1 red small' %></li>
    </ul>
  </div>
</div>

app/views/users/posts/new.html.erb
<% provide(:body_class, 'posts-edit') %>
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="/users/dashboard">Консоль</a>
    </li>
    <li class="breadcrumb-item">
      <a href="/users/posts">Записи</a>
    </li>
    <li class="breadcrumb-item active">Новая запись</li>
  </ol>

  <%= form_with model: @post, url: users_posts_path, local: true do |f| %>
    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2>Основная информация</h2>
        <%= f.submit "Сохранить", class: "btn_1 small pull-right" %>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Название</label>
            <%= f.text_field :title, class: "form-control", placeholder: "Название записи" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Описание</label>
            <%= f.text_area :description, class: "form-control tinymce", placeholder: "Описание", rows: 15 %>
          </div>
        </div>
      </div>
    </div>
    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2>SEO</h2>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Meta title</label>
            <%= f.text_field :meta_title, class: "form-control", placeholder: "meta title" %>
          </div>
          <div class="form-group">
            <label>Meta description</label>
            <%= f.text_area :meta_description, class: "form-control", placeholder: "meta description" %>
          </div>
          <div class="form-group">
            <label>Meta keywords</label>
            <%= f.text_area :meta_keywords, class: "form-control", placeholder: "meta keywords" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="buttons_container">
    <ul>
      <li><%= link_to "Назад", users_posts_path, class: 'btn_1 gray small' %></li>
    </ul>
  </div>
</div>